CREATE TABLE master.dbo.USERS (
	ID_USERS bigint IDENTITY(1,1) NOT NULL,
	USER_NAME varchar(100) NOT NULL,
	USER_PASS varchar(100) NOT NULL,
	CONSTRAINT USERS_PK PRIMARY KEY (ID_USERS)
);

CREATE TABLE master.dbo.TASK (
	ID_TASK bigint IDENTITY(1,1) NOT NULL,
	DESCRIPTION varchar(100) NOT NULL,
  PRIORITY smallint DEFAULT 0 NOT NULL;
	STATUS smallint DEFAULT 0 NOT NULL,
	CREATED datetime NOT NULL,
	FINISHED datetime NULL,
	CONSTRAINT TASK_PK PRIMARY KEY (ID_TASK)
);

INSERT INTO master.dbo.USERS(USER_NAME, USER_PASS) VALUES('admin', '21232f297a57a5a743894a0e4a801fc3');
INSERT INTO master.dbo.USERS(USER_NAME, USER_PASS) VALUES('user1', '24c9e15e52afc47c225b757e7bee1f9d');
